### ISSUE TITLE
Chat Export Theme

### ISSUE THREAD

**Issue by timea-techgirl** [VChet/telegram-vanilla-dark-desktop#59]
Hey! Thanks for the nice themes. :) I would like to kindly request a dark theme for the exported chat history. Currently it's blinding white and I requested Telegram countless times for a dark version of chat export. They did nothing about it. I edited the colours in style.css and managed to turn the history dark but I'm sure you can do it better. Here is the original css file.

[style.zip](https://github.com/VChet/Telegram-Vanilla-Dark-Desktop/files/9484784/style.zip)

Hope you have time to do it. Thanks! :)

**Comment by VChet** [comment]
Hi!

Unfortunately, I don't have time to write all the styles by hand and customize them, mainly because I don't use Telegram's chat export feature myself. But I created a repo with a remap script for the current style: https://github.com/VChet/telegram-export-dark

It already has all 4 color themes ready to use and if you want you may customize it to support more colors or even create your own theme.

I'm closing this issue, if you'll have problems or suggestions with those themes, feel free to create a new issue at https://github.com/VChet/telegram-export-dark.
